name: user_repository
description: Dart pa that manages the user
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5

  # Firebase
  firebase_auth: ^4.11.1
  cloud_firestore: ^4.11.0
  firebase_storage: ^11.1.0
  firebase_core: ^2.9.0
#  firebase_for_all: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
