name: fo_fe
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: 13.2.0
  bloc_test: ^9.1.6

  #firebase_core:
  firebase_core: ^2.22.0

  #  firebase_for_all: ^0.1.1

  objectbox: ^2.4.0
  objectbox_flutter_libs: any
  intl: any

  # local packages
  #  organizer:
  #    path: packages/organizer
  user_repository:
    path: packages/user_repository
  authentication:
    path: packages/authentication
  #  tasks:
  #     path: packages/tasks

  # Service locator
  get_it: ^7.6.7
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  data_connection_checker_nulls: ^0.0.2
  http: ^1.2.0
  # Local cache
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4


  build_runner: ^2.4.8

  objectbox_generator: any

#  dependency_overrides:
#    firebase_core_platform_interface: 4.5.1


flutter:
  uses-material-design: true
