name: fo_fe
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^12.1.1

  #firebase_core:
  firebase_core: ^2.22.0

  # local packages
  organizer:
    path: packages/organizer

  user_repository:
    path: packages/user_repository
  authentication:
    path: packages/authentication

dev_dependencies:
  flutter_lints: ^ 3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
