= User

=== ToDecede

* how to set the name of the user that appear for each user
** using nickname
** using the userUser table nickname

== Decided User

=== UserType

Local: Users whose accounts are created and used only on the current device. They don’t sync with any remote server.
mandatory name and password
can have email

Remote: Users who exist on a server and are accessible across multiple devices. They don’t have a full profile locally but can interact with local users.
mandatory name and email verified by email
can have password

Temporary: Users created offline with minimal information. They have restricted access and can be converted to a synced user upon connection to the internet.
mandatory name
can have email and password

Synced (or Hybrid): Local users who are also registered on the server, allowing them to sync data and access their account from other devices.
mandatory name and email and password verified  and sync with remote

== Decide UserUser

* If it’s mostly passive (e.g., user associations stored in a database), use link.
* If it’s mostly active (e.g., real-time connections in a social or chat app), use connected.

* I will use link for userUser and connect when I will create the chat



=== userNameLinked

* is the name that this user is setting to linked user and is the first name of the user

=== userStatus

* Pending, the invitation was send
* Accepted, Rejected,  the invitation
* Blocked the user is blocked

whe you respond the invitation another line will be create d with the status and also the nikname
that you give it to the user that you respond

==Worked

241109
* if the name pasword and email are changing from a valid format name or password to an invalid
state to be shown a message that the name or password is invalid