// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Fy_2bVGfrUMsH1Zbm9xly9XsXX9JdmE',
    appId: '1:898234815807:web:3f0130d9b440237b402f8a',
    messagingSenderId: '898234815807',
    projectId: 'fo-fe-a120a',
    authDomain: 'fo-fe-a120a.firebaseapp.com',
    storageBucket: 'fo-fe-a120a.appspot.com',
    measurementId: 'G-1JE330D0LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHG1TfluCR0jURBxMctomJjbe3UJKVQ0s',
    appId: '1:898234815807:android:2df38e7dad441a4d402f8a',
    messagingSenderId: '898234815807',
    projectId: 'fo-fe-a120a',
    storageBucket: 'fo-fe-a120a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2kgWnw9JnXlPOfmDGyvB4UzhOVVNR1co',
    appId: '1:898234815807:ios:998f0647ef67cfac402f8a',
    messagingSenderId: '898234815807',
    projectId: 'fo-fe-a120a',
    storageBucket: 'fo-fe-a120a.appspot.com',
    iosBundleId: 'com.example.foFe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2kgWnw9JnXlPOfmDGyvB4UzhOVVNR1co',
    appId: '1:898234815807:ios:52645e6f86201466402f8a',
    messagingSenderId: '898234815807',
    projectId: 'fo-fe-a120a',
    storageBucket: 'fo-fe-a120a.appspot.com',
    iosBundleId: 'com.example.foFe.RunnerTests',
  );
}
