// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwxOF9KeN4SjIQF__sL_sQW_4IJDgtqIE',
    appId: '1:312570564124:web:07084737f2bfd590e7d9d9',
    messagingSenderId: '312570564124',
    projectId: 'fo-fe-57e85',
    authDomain: 'fo-fe-57e85.firebaseapp.com',
    storageBucket: 'fo-fe-57e85.appspot.com',
    measurementId: 'G-3HEMEVY1RH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDej5sx126igwrR3M_cKVbBSKVF0sgfbrg',
    appId: '1:312570564124:android:fd4c0618a703feeae7d9d9',
    messagingSenderId: '312570564124',
    projectId: 'fo-fe-57e85',
    storageBucket: 'fo-fe-57e85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi2QmZUAvSyiVqw5C4AviY4dFjbB5eHY8',
    appId: '1:312570564124:ios:6f797179487159a5e7d9d9',
    messagingSenderId: '312570564124',
    projectId: 'fo-fe-57e85',
    storageBucket: 'fo-fe-57e85.appspot.com',
    iosBundleId: 'com.example.foFe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi2QmZUAvSyiVqw5C4AviY4dFjbB5eHY8',
    appId: '1:312570564124:ios:db91a8b0cefc5151e7d9d9',
    messagingSenderId: '312570564124',
    projectId: 'fo-fe-57e85',
    storageBucket: 'fo-fe-57e85.appspot.com',
    iosBundleId: 'com.example.foFe.RunnerTests',
  );
}
