=== Auth namings

* shall be used all the time short form auth


==== AuthSignFailedBlocState

* AuthSignFailedBlocState is a new state you can create to represent a specific failure in the
auth process, with an error property to store the error message.
* AuthSignErrorBlocState is an existing state that also represents an error in the auth
process, with a message property to store the error message.
* Both states serve a similar purpose but may be used in different contexts or to represent
different types of errors.

=== Auth Entity

* refreshCount = every time the user is log out and log in again, the refresh count will be
increased by 1
* isActive = true if the user is active, false if the user is inactive (log out)
* isAutoSignIn = true if the user is log in automatically and is not nedd to enter the password
* _refreshMax = the maximum number of refresh count

=== Sign In

* is cherching if the user and passwoords are valid
* get useridby name and passwpord
* check if there is an autehntication with user id on device
** return existing auth
** create new auth

=== Auto Sign In

* get the latest auth for that device
* if token is not expired
** return the auth
** Send mesage the token expired log in again

=== Sign Out

* check if the refrresh count is the same as the max refreshCount or expire date is due.
** if yes, delete the auth
** if no, set active to no

=== Sign Up

first check if the user exist if yes an error mesage is send
if the user do not exist add user
if during adding an error ocure send a message
if user added try to sign up if an error ocure send a message and delete the user
if the user is signed up send a message

=== Presentation

* to don't increment usles the view count use get auth
?? is the state from app_bar_widget incrising the coutn or is just reading from the latest state?

== Log from Sign

* I change the name from log to sign because it is more clear what is the purpose of the class.
* I grouped all the log bloc in one bloc and let out the sign up
* I use stats like LogInSuccess for a more specific state and AuthenticatedState  for a global
state . I need this distinction so that I know how many auto log in I have and to use it in _usedCountMax

